package DRSCommon;


/**
* DRSCommon/DRSCommonServicePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/workspace/comp6231ass2/src/DRSCommon.idl
* Saturday, October 27, 2012 6:12:47 PM EDT
*/

public class DRSCommonServicePOATie extends DRSCommonServicePOA
{

  // Constructors

  public DRSCommonServicePOATie ( DRSCommon.DRSCommonServiceOperations delegate ) {
      this._impl = delegate;
  }
  public DRSCommonServicePOATie ( DRSCommon.DRSCommonServiceOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public DRSCommon.DRSCommonServiceOperations _delegate() {
      return this._impl;
  }
  public void _delegate (DRSCommon.DRSCommonServiceOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int buy (String customerID, String itemID, int numberOfItem)
  {
    return _impl.buy(customerID, itemID, numberOfItem);
  } // buy

  public int returnNumOfItem (String customerID, String itemID, int numberOfItem)
  {
    return _impl.returnNumOfItem(customerID, itemID, numberOfItem);
  } // returnNumOfItem

  public String checkStock (String itemID)
  {
    return _impl.checkStock(itemID);
  } // checkStock

  public int exchange (String customerID, String boughtItemID, int boughtNumber, String desiredItemID, int desiredNumber)
  {
    return _impl.exchange(customerID, boughtItemID, boughtNumber, desiredItemID, desiredNumber);
  } // exchange

  private DRSCommon.DRSCommonServiceOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class DRSCommonServicePOATie
