package DRSCommon;


/**
* DRSCommon/DRSCommonService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/workspace/comp6231ass2/src/DRSCommon.idl
* Saturday, October 27, 2012 6:12:47 PM EDT
*/

public interface DRSCommonService extends DRSCommonServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DRSCommonService
