package DRSCommon;


/**
* DRSCommon/_DRSCommonServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/workspace/comp6231ass2/src/DRSCommon.idl
* Saturday, October 27, 2012 6:12:47 PM EDT
*/

public class _DRSCommonServiceStub extends org.omg.CORBA.portable.ObjectImpl implements DRSCommon.DRSCommonService
{

  public int buy (String customerID, String itemID, int numberOfItem)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("buy", true);
                $out.write_string (customerID);
                $out.write_string (itemID);
                $out.write_long (numberOfItem);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return buy (customerID, itemID, numberOfItem        );
            } finally {
                _releaseReply ($in);
            }
  } // buy

  public int returnNumOfItem (String customerID, String itemID, int numberOfItem)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("returnNumOfItem", true);
                $out.write_string (customerID);
                $out.write_string (itemID);
                $out.write_long (numberOfItem);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return returnNumOfItem (customerID, itemID, numberOfItem        );
            } finally {
                _releaseReply ($in);
            }
  } // returnNumOfItem

  public String checkStock (String itemID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("checkStock", true);
                $out.write_string (itemID);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return checkStock (itemID        );
            } finally {
                _releaseReply ($in);
            }
  } // checkStock

  public int exchange (String customerID, String boughtItemID, int boughtNumber, String desiredItemID, int desiredNumber)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("exchange", true);
                $out.write_string (customerID);
                $out.write_string (boughtItemID);
                $out.write_long (boughtNumber);
                $out.write_string (desiredItemID);
                $out.write_long (desiredNumber);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return exchange (customerID, boughtItemID, boughtNumber, desiredItemID, desiredNumber        );
            } finally {
                _releaseReply ($in);
            }
  } // exchange

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DRSCommon/DRSCommonService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _DRSCommonServiceStub
