package DRSCommon;

/**
* DRSCommon/DRSCommonServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/workspace/comp6231ass2/src/DRSCommon.idl
* Saturday, October 27, 2012 6:12:47 PM EDT
*/

public final class DRSCommonServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public DRSCommon.DRSCommonService value = null;

  public DRSCommonServiceHolder ()
  {
  }

  public DRSCommonServiceHolder (DRSCommon.DRSCommonService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DRSCommon.DRSCommonServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DRSCommon.DRSCommonServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DRSCommon.DRSCommonServiceHelper.type ();
  }

}
