package DRSCommon;


/**
* DRSCommon/DRSCommonServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/workspace/comp6231ass2/src/DRSCommon.idl
* Saturday, October 27, 2012 6:12:47 PM EDT
*/

public interface DRSCommonServiceOperations 
{
  int buy (String customerID, String itemID, int numberOfItem);
  int returnNumOfItem (String customerID, String itemID, int numberOfItem);
  String checkStock (String itemID);
  int exchange (String customerID, String boughtItemID, int boughtNumber, String desiredItemID, int desiredNumber);
} // interface DRSCommonServiceOperations
