// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package server;

public final class DRSServerImpl_Stub
    extends java.rmi.server.RemoteStub
    implements common.DRSCommon, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_buy_0;
    private static java.lang.reflect.Method $method_checkStock_1;
    private static java.lang.reflect.Method $method_returnNumOfItem_2;
    
    static {
	try {
	    $method_buy_0 = common.DRSCommon.class.getMethod("buy", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, int.class});
	    $method_checkStock_1 = common.DRSCommon.class.getMethod("checkStock", new java.lang.Class[] {java.lang.String.class});
	    $method_returnNumOfItem_2 = common.DRSCommon.class.getMethod("returnNumOfItem", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, int.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public DRSServerImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of buy(String, String, int)
    public int buy(java.lang.String $param_String_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_buy_0, new java.lang.Object[] {$param_String_1, $param_String_2, new java.lang.Integer($param_int_3)}, 1962698059928648901L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of checkStock(String)
    public java.lang.String checkStock(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_checkStock_1, new java.lang.Object[] {$param_String_1}, -4779678296372021959L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of returnNumOfItem(String, String, int)
    public int returnNumOfItem(java.lang.String $param_String_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_returnNumOfItem_2, new java.lang.Object[] {$param_String_1, $param_String_2, new java.lang.Integer($param_int_3)}, 1078605600006335805L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
