package exe;
/*
 * The client implementation is generated by the ORB Studio.
 */
import java.io.PrintWriter;
import java.io.StringWriter;

import DRSCommon.DRSClientCommon;
import DRSCommon.DRSServerCommon;

import common.SvrInfo;
import common.SysLogger;

class Client {
	
	/**
	 * Test driver for DRSCommonServiceClientImpl.
	 * 
	 * @param args
	 */
	public static void main(String[] args) {
		// initialize SysLogger
		SysLogger.init("client.txt");
		
		try {
			// simple test
			// one customer, one item, three stores
			String svrName = SvrInfo.SVR_NAME_MONTREAL;
			String customerID = "M10001";
			String itemID = DRSServerCommon.TEST_ITEMID;
			int numberOfItem = 10;
			
			ConcurrentTest t = new ConcurrentTest(svrName, customerID, itemID, numberOfItem);
			t.simpleTest(svrName, customerID, itemID, numberOfItem);


			// concurrent test 
			// three users concurrently accessing one item
			itemID = DRSServerCommon.TEST_ITEMID_CON;
			
			ConcurrentTest.concurrentTest(SvrInfo.SVR_NAME_MONTREAL, "M10001", itemID, numberOfItem);
			ConcurrentTest.concurrentTest(SvrInfo.SVR_NAME_TORONTO, "T10001", itemID, numberOfItem);
			ConcurrentTest.concurrentTest(SvrInfo.SVR_NAME_VANCOUVER, "V10001", itemID, numberOfItem);
			
			if (ConcurrentTest.t1 != null) {
				ConcurrentTest.t1.join();
			}
			if (ConcurrentTest.t2 != null) {
				ConcurrentTest.t2.join();
			}
			if (ConcurrentTest.t2 != null) {
				ConcurrentTest.t3.join();
			}
		} catch (Exception e) {
			StringWriter err = new StringWriter();
			e.printStackTrace(new PrintWriter(err));
			SysLogger.err(err.toString());
		}

	}
}
