/*
 * COMP6421 Project
 *  
 * This file is created by Yuan Tao (ewan.msn@gmail.com)
 * Licensed under GNU GPL v3
 * 
 * $Author$
 * $Date$
 * $Rev$
 * $HeadURL$
 * 
 */

package LexicalAnalyzer;

public class Token {
	public String file = null;		// file name
	public int line = 0;			// line number
	public int column = 0;			// the column of the first character
	public String token = null;		// 
	public int type;				//  
	
	public boolean error = false;	// true means the token is generated by error recovery technique

}
