package ca.com.Concordia.distributed.Ass_2.MyServer;


/**
* MyServer/_MyServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/work/DRS_CORBA/simple.idl
* Thursday, November 29, 2012 4:20:37 o'clock PM CST
*/

public class _MyServiceStub extends org.omg.CORBA.portable.ObjectImpl implements ca.com.Concordia.distributed.Ass_2.MyServer.MyService
{

  public String purchase (int customerID, String itemID, int numberOfItem)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("purchase", true);
                $out.write_long (customerID);
                $out.write_string (itemID);
                $out.write_long (numberOfItem);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return purchase (customerID, itemID, numberOfItem        );
            } finally {
                _releaseReply ($in);
            }
  } // purchase

  public String giveback (int customerID, String itemID, int numberOfItem)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("giveback", true);
                $out.write_long (customerID);
                $out.write_string (itemID);
                $out.write_long (numberOfItem);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return giveback (customerID, itemID, numberOfItem        );
            } finally {
                _releaseReply ($in);
            }
  } // giveback

  public int checkStock (String itemID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("checkStock", true);
                $out.write_string (itemID);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return checkStock (itemID        );
            } finally {
                _releaseReply ($in);
            }
  } // checkStock

  public boolean haveThisItem (String itemID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("haveThisItem", true);
                $out.write_string (itemID);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return haveThisItem (itemID        );
            } finally {
                _releaseReply ($in);
            }
  } // haveThisItem

  public String exChange (String itemID1, String itemID2, int customerID, int numberOfItem)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("exChange", true);
                $out.write_string (itemID1);
                $out.write_string (itemID2);
                $out.write_long (customerID);
                $out.write_long (numberOfItem);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return exChange (itemID1, itemID2, customerID, numberOfItem        );
            } finally {
                _releaseReply ($in);
            }
  } // exChange

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MyServer/MyService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _MyServiceStub
