package ca.com.Concordia.distributed.Ass_2.MyServer;


/**
* MyServer/MyServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/work/DRS_CORBA/simple.idl
* Thursday, November 29, 2012 4:20:37 o'clock PM CST
*/

abstract public class MyServiceHelper
{
  private static String  _id = "IDL:MyServer/MyService:1.0";

  public static void insert (org.omg.CORBA.Any a, ca.com.Concordia.distributed.Ass_2.MyServer.MyService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ca.com.Concordia.distributed.Ass_2.MyServer.MyService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ca.com.Concordia.distributed.Ass_2.MyServer.MyServiceHelper.id (), "MyService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ca.com.Concordia.distributed.Ass_2.MyServer.MyService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MyServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ca.com.Concordia.distributed.Ass_2.MyServer.MyService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ca.com.Concordia.distributed.Ass_2.MyServer.MyService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ca.com.Concordia.distributed.Ass_2.MyServer.MyService)
      return (ca.com.Concordia.distributed.Ass_2.MyServer.MyService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ca.com.Concordia.distributed.Ass_2.MyServer._MyServiceStub stub = new ca.com.Concordia.distributed.Ass_2.MyServer._MyServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ca.com.Concordia.distributed.Ass_2.MyServer.MyService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ca.com.Concordia.distributed.Ass_2.MyServer.MyService)
      return (ca.com.Concordia.distributed.Ass_2.MyServer.MyService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ca.com.Concordia.distributed.Ass_2.MyServer._MyServiceStub stub = new ca.com.Concordia.distributed.Ass_2.MyServer._MyServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
