package ca.com.Concordia.distributed.Ass_2.MyServer;


/**
* MyServer/MyServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/work/DRS_CORBA/simple.idl
* Thursday, November 29, 2012 4:20:37 o'clock PM CST
*/

public interface MyServiceOperations 
{
  String purchase (int customerID, String itemID, int numberOfItem);
  String giveback (int customerID, String itemID, int numberOfItem);
  int checkStock (String itemID);
  boolean haveThisItem (String itemID);
  String exChange (String itemID1, String itemID2, int customerID, int numberOfItem);
} // interface MyServiceOperations
