package ca.com.Concordia.distributed.Ass_2.MyServer;


/**
* MyServer/MyService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/work/DRS_CORBA/simple.idl
* Thursday, November 29, 2012 4:20:37 o'clock PM CST
*/

public interface MyService extends MyServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MyService
