package ca.com.Concordia.distributed.Ass_2.MyServer;


/**
* MyServer/MyServicePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/work/DRS_CORBA/simple.idl
* Thursday, November 29, 2012 4:20:37 o'clock PM CST
*/

public class MyServicePOATie extends MyServicePOA
{

  // Constructors

  public MyServicePOATie ( ca.com.Concordia.distributed.Ass_2.MyServer.MyServiceOperations delegate ) {
      this._impl = delegate;
  }
  public MyServicePOATie ( ca.com.Concordia.distributed.Ass_2.MyServer.MyServiceOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public ca.com.Concordia.distributed.Ass_2.MyServer.MyServiceOperations _delegate() {
      return this._impl;
  }
  public void _delegate (ca.com.Concordia.distributed.Ass_2.MyServer.MyServiceOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String purchase (int customerID, String itemID, int numberOfItem)
  {
    return _impl.purchase(customerID, itemID, numberOfItem);
  } // purchase

  public String giveback (int customerID, String itemID, int numberOfItem)
  {
    return _impl.giveback(customerID, itemID, numberOfItem);
  } // giveback

  public int checkStock (String itemID)
  {
    return _impl.checkStock(itemID);
  } // checkStock

  public boolean haveThisItem (String itemID)
  {
    return _impl.haveThisItem(itemID);
  } // haveThisItem

  public String exChange (String itemID1, String itemID2, int customerID, int numberOfItem)
  {
    return _impl.exChange(itemID1, itemID2, customerID, numberOfItem);
  } // exChange

  private ca.com.Concordia.distributed.Ass_2.MyServer.MyServiceOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class MyServicePOATie
