package ca.com.Concordia.distributed.Ass_2.MyServer;

/**
* MyServer/MyServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/work/DRS_CORBA/simple.idl
* Thursday, November 29, 2012 4:20:37 o'clock PM CST
*/

public final class MyServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public ca.com.Concordia.distributed.Ass_2.MyServer.MyService value = null;

  public MyServiceHolder ()
  {
  }

  public MyServiceHolder (ca.com.Concordia.distributed.Ass_2.MyServer.MyService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ca.com.Concordia.distributed.Ass_2.MyServer.MyServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ca.com.Concordia.distributed.Ass_2.MyServer.MyServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ca.com.Concordia.distributed.Ass_2.MyServer.MyServiceHelper.type ();
  }

}
